# Test cases automatically generated by Pynguin (https://github.com/se2p/pynguin).
# Please check them before you use them.
import pytest
import add_bug2 as module_0
import builtins as module_1


def test_case_0():
    float_0 = -3641.8
    var_0 = module_0.add(float_0, float_0)
    assert var_0 == 0


@pytest.mark.xfail(strict=True)
def test_case_1():
    object_0 = module_1.object()
    str_0 = "',G(LN4\n6;SUWr$>"
    module_0.add(object_0, str_0)
