# Test cases automatically generated by Pynguin (https://github.com/se2p/pynguin).
# Please check them before you use them.
import add_bug2_types as module_0


def test_case_0():
    bool_0 = False
    int_0 = module_0.add(bool_0, bool_0)
    assert int_0 == 0


def test_case_1():
    bool_0 = False
    int_0 = 2974
    int_1 = module_0.add(bool_0, int_0)
    assert int_1 == 2974
