# Test cases automatically generated by Pynguin (https://github.com/se2p/pynguin).
# Please check them before you use them.
import pytest
import sneaky_div as module_0


def test_case_0():
    float_0 = 6996.330658522424
    bool_0 = False
    var_0 = module_0.sneaky_div(float_0, bool_0)
    assert var_0 == pytest.approx(6996.330658522424, abs=0.01, rel=0.01)


def test_case_1():
    float_0 = 7079.127123951987
    object_0 = module_0.sneaky_div(float_0, float_0)
    assert object_0 == pytest.approx(7079.127123951987, abs=0.01, rel=0.01)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = 10009
    module_0.sneaky_div(int_0, int_0)
