# Test cases automatically generated by Pynguin (https://github.com/se2p/pynguin).
# Please check them before you use them.
import count as module_0


def test_case_0():
    none_type_0 = None
    module_0.count(none_type_0, none_type_0)
