# Test cases automatically generated by Pynguin (https://github.com/se2p/pynguin).
# Please check them before you use them.
import count_types as module_0


def test_case_0():
    list_0 = []
    str_0 = "6"
    int_0 = module_0.count(list_0, str_0)
