# Test cases automatically generated by Pynguin (https://github.com/se2p/pynguin).
# Please check them before you use them.
import choice as module_0


def test_case_0():
    bool_0 = True
    module_0.choice(bool_0)
