# Test cases automatically generated by Pynguin (https://github.com/se2p/pynguin).
# Please check them before you use them.
import builtins as module_0
import choice_types as module_1


def test_case_0():
    object_0 = module_0.object()
    module_1.choice(object_0)
