# Test cases automatically generated by Pynguin (https://github.com/se2p/pynguin).
# Please check them before you use them.
import pytest
import uninterpretable_types as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    int_0 = 764
    var_0 = module_0.foo(int_0)
    assert var_0 == 3
    module_0.foo(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    module_0.foo(bool_0)
