# Test cases automatically generated by Pynguin (https://github.com/se2p/pynguin).
# Please check them before you use them.
import pytest
import uninterpretable as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    float_0 = 564.1425
    var_0 = module_0.foo(float_0)
    assert var_0 == 3
    complex_0 = 126.2 + 3669.1j
    var_1 = module_0.foo(float_0)
    assert var_1 == 3
    module_0.foo(complex_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    module_0.foo(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    object_0 = module_1.object()
    module_0.foo(object_0)
